### ISSUE TITLE
lcd color change

### ISSUE THREAD

**Issue by Dev4sure** [zwliew/android_device_xiaomi_hm2014811#77]
Display color changes after screen wake up.

**Comment by zwliew** [comment]
fixed by kumajaya

**Comment by mueedqadri** [comment]
I downloaded the latest build but i am still having this issue

**Comment by zwliew** [comment]
Download the fixed boot.img in my latest post on the XDA thread. Full update will be released by the end of the week.

**Comment by VIZ-KILLER** [comment]
The new kernel solved the issue
